version: "3.9"

services:
  logdip:
    image: '${DOCKER_IMAGE_PREFIX?Variable not set}logdip:rolling'
    build:
      context: .
      dockerfile: dockerfiles/logdip.dockerfile
      args:
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX?Variable not set}
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - traefik-public
    env_file:
      - ./.env
  db:
    image: '${DOCKER_IMAGE_PREFIX?Variable not set}postgres:14'
    # restart: on-fali
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      # THIS IS UNSAFE!
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - traefik-public
    ports:
      - 5432:5432

networks:
  traefik-public:
    external: true

volumes:
  app-db-data:
