version: "3.9"

services:
  logbeam:
    image: '${DOCKER_IMAGE_PREFIX?Variable not set}logbeam:rolling'
    build:
      context: .
      dockerfile: dockerfiles/logbeam.dockerfile
      args:
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX?Variable not set}
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - traefik-public
    env_file:
      - ./.env

networks:
  traefik-public:
    external: true

volumes:
  app-db-data:
