openapi: "3.1.0"
info:
  description: API for logbeam
  license:
    name: MIT
    identifier: MIT
    url: LICENSE
  title: LogBeam API
  version: "0.0.2"
servers:
  - url: http://localhost:9010/api

components:
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    $ref: './schemas/_index.yml'

  securitySchemes:
    BearerAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Token-based authentication with required prefix "Token"
    FluentdBasicAuth:
      type: http
      scheme: basic
      description: >
        Fluentd basic auth.

paths:
  /auth/token:
    $ref: "./paths/auth/token.yml"
  /input/fluentd:
    $ref: "./paths/input/fluentd.yml"
  /log/range:
    $ref: "./paths/log/range.yml"
